site_name: Demonsaw Guide
pages:
- Home: index.md
- Client Setup: 'client/index.md'
- Router Setup: 'router/index.md'
- Headless Setup: 'headless.md'
- Troubleshooting:
   - 'Client': 'client/troubleshooting.md'
   - 'Router': 'router/troubleshooting.md'
- Resources: resources.md
theme: slate
