site_name: Demonsaw Docs
site_description: "Demonsaw documentation and user guides."
site_author: 'The Community'
repo_name: GitHub
repo_url: https://github.com/demonsaw/documentation
theme: cyborg

extra_css:
   - css/changes.css
extra_javascript:

pages:
- Home: index.md
- Client Docs:
   - 'Getting Started': 'client/index.md'
   - 'Headless Setup': 'client/headless.md'
   - 'Troubleshooting': 'client/troubleshooting.md'
- Router Docs:
   - 'Getting Started': 'router/index.md'
   - 'Headless Setup': 'router/headless.md'
   - 'Troubleshooting': 'router/troubleshooting.md'
- More:
   - 'Extra Resources' : 'resources.md'
   - 'Demonsaw FAQ': 'FAQ.md'
   - 'DS 3.0 Features': 'features.md'
